[package]
name = "hunk-qt"
version = "0.0.11"
license.workspace = true
edition = "2024"
authors = ["Nitesh Balusu"]
build = "build.rs"

[[bin]]
name = "hunk_qt"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
hunk-domain = { path = "../hunk-domain", default-features = false }
hunk-forge = { path = "../hunk-forge" }
hunk-git = { path = "../hunk-git" }
qtbridge.workspace = true
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.5"
